// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/payment/payment.proto

package go_micro_secbuy_srv_payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayEvent struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State                int32    `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayEvent) Reset()         { *m = PayEvent{} }
func (m *PayEvent) String() string { return proto.CompactTextString(m) }
func (*PayEvent) ProtoMessage()    {}
func (*PayEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{0}
}

func (m *PayEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayEvent.Unmarshal(m, b)
}
func (m *PayEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayEvent.Marshal(b, m, deterministic)
}
func (m *PayEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayEvent.Merge(m, src)
}
func (m *PayEvent) XXX_Size() int {
	return xxx_messageInfo_PayEvent.Size(m)
}
func (m *PayEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PayEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PayEvent proto.InternalMessageInfo

func (m *PayEvent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PayEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PayEvent) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type Payment struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State                int32    `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{1}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Payment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Payment) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Payment) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type Request struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payment              *Payment `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*PayEvent)(nil), "go.micro.secbuy.srv.payment.PayEvent")
	proto.RegisterType((*Payment)(nil), "go.micro.secbuy.srv.payment.Payment")
	proto.RegisterType((*Request)(nil), "go.micro.secbuy.srv.payment.Request")
	proto.RegisterType((*Response)(nil), "go.micro.secbuy.srv.payment.Response")
	proto.RegisterType((*Error)(nil), "go.micro.secbuy.srv.payment.Error")
}

func init() { proto.RegisterFile("proto/payment/payment.proto", fileDescriptor_78ce6d11f0608d17) }

var fileDescriptor_78ce6d11f0608d17 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0x5c, 0xd7, 0xf9, 0x06, 0x3b, 0x3c, 0x44, 0xaa, 0x03, 0x19, 0x41, 0x61, 0xa7,
	0x08, 0xdb, 0xc5, 0x93, 0x27, 0x77, 0x76, 0x44, 0xc1, 0x73, 0x96, 0x3e, 0x24, 0x60, 0x9b, 0x9a,
	0xa4, 0x85, 0xfe, 0x33, 0xfe, 0xad, 0xb2, 0x34, 0x05, 0x41, 0xa8, 0xe0, 0x29, 0xef, 0x3d, 0xbe,
	0xf7, 0xe5, 0xe3, 0x97, 0xc0, 0xaa, 0xb6, 0xc6, 0x9b, 0xfb, 0x5a, 0x76, 0x25, 0x55, 0x7e, 0x38,
	0x79, 0x98, 0xe2, 0xea, 0xdd, 0xf0, 0x52, 0x2b, 0x6b, 0xb8, 0x23, 0x75, 0x6c, 0x3a, 0xee, 0x6c,
	0xcb, 0xa3, 0x84, 0x3d, 0xc1, 0xfc, 0x20, 0xbb, 0x7d, 0x4b, 0x95, 0xc7, 0x25, 0x4c, 0x74, 0x91,
	0x27, 0xeb, 0x64, 0x93, 0x8a, 0x89, 0x2e, 0x10, 0x61, 0x5a, 0xc9, 0x92, 0xf2, 0xc9, 0x3a, 0xd9,
	0x9c, 0x8b, 0x50, 0xe3, 0x05, 0xa4, 0xce, 0x4b, 0x4f, 0xf9, 0x59, 0x90, 0xf5, 0x0d, 0x53, 0x90,
	0x1d, 0x7a, 0xc3, 0xff, 0x9b, 0xe0, 0x0d, 0x80, 0xb2, 0x24, 0x3d, 0xbd, 0xea, 0x92, 0xf2, 0x69,
	0xd0, 0xff, 0x98, 0xb0, 0x2b, 0xc8, 0x04, 0x7d, 0x36, 0xe4, 0x7e, 0x5d, 0xc2, 0xbe, 0x12, 0x98,
	0x0b, 0x72, 0xb5, 0xa9, 0x1c, 0x61, 0x0e, 0x99, 0x6b, 0x94, 0x22, 0xe7, 0x82, 0x62, 0x2e, 0x86,
	0x16, 0x1f, 0x20, 0x25, 0x6b, 0x8d, 0x0d, 0x61, 0x16, 0x5b, 0xc6, 0x47, 0xc8, 0xf0, 0xfd, 0x49,
	0x29, 0xfa, 0x05, 0x7c, 0x84, 0x2c, 0xce, 0x43, 0xe6, 0xc5, 0xf6, 0x76, 0x74, 0x37, 0xc2, 0x10,
	0xc3, 0x12, 0xdb, 0x41, 0x1a, 0xfc, 0x4e, 0x38, 0x94, 0x29, 0x28, 0x66, 0x0f, 0x35, 0x5e, 0xc2,
	0xac, 0x20, 0x2f, 0xf5, 0x47, 0x84, 0x14, 0xbb, 0xad, 0x86, 0x65, 0x34, 0x7a, 0x21, 0xdb, 0x6a,
	0x45, 0xf8, 0x16, 0x5e, 0xeb, 0xd9, 0x16, 0x64, 0x71, 0x3c, 0x41, 0x24, 0x75, 0x7d, 0xf7, 0x87,
	0xaa, 0x67, 0x76, 0x9c, 0x85, 0xaf, 0xb2, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x84, 0xc3,
	0x0f, 0x49, 0x02, 0x00, 0x00,
}
