// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

package go_micro_secbuy_srv_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 购买商品 ID
type GetRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 结果
type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Order                *Order   `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// 错误信息
type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

// 订单信息
type Order struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{3}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "go.micro.secbuy.srv.order.GetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.secbuy.srv.order.Response")
	proto.RegisterType((*Error)(nil), "go.micro.secbuy.srv.order.Error")
	proto.RegisterType((*Order)(nil), "go.micro.secbuy.srv.order.Order")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor_986e030a471601a2) }

var fileDescriptor_986e030a471601a2 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x49, 0x34, 0xb5, 0x9d, 0x8a, 0x87, 0x39, 0x68, 0x14, 0x91, 0x10, 0x11, 0x7a, 0x5a,
	0xa1, 0x05, 0x5f, 0x40, 0xc4, 0x83, 0x07, 0x61, 0xf5, 0xe2, 0x31, 0xdd, 0x1d, 0x64, 0xc1, 0x74,
	0xeb, 0xec, 0xa6, 0xe0, 0x7b, 0xf8, 0xc0, 0x92, 0xd9, 0x14, 0x45, 0xb0, 0x5e, 0x86, 0x99, 0xd9,
	0xdf, 0xfc, 0xe7, 0x63, 0xe1, 0x64, 0xcd, 0x3e, 0xfa, 0x6b, 0xcf, 0x96, 0x38, 0x59, 0x25, 0x19,
	0x3c, 0x7d, 0xf5, 0xaa, 0x75, 0x86, 0xbd, 0x0a, 0x64, 0x96, 0xdd, 0x87, 0x0a, 0xbc, 0x51, 0x02,
	0xd4, 0xe7, 0x00, 0xf7, 0x14, 0x35, 0xbd, 0x77, 0x14, 0x22, 0x1e, 0x41, 0xee, 0x6c, 0x99, 0x55,
	0xd9, 0xac, 0xd0, 0xb9, 0xb3, 0xf5, 0x67, 0x06, 0x63, 0x4d, 0x61, 0xed, 0x57, 0x81, 0xb0, 0x84,
	0x83, 0xd0, 0x19, 0x43, 0x21, 0x08, 0x31, 0xd6, 0xdb, 0x10, 0x6f, 0xa0, 0x20, 0x66, 0xcf, 0x65,
	0x5e, 0x65, 0xb3, 0xe9, 0xbc, 0x52, 0x7f, 0xf6, 0x53, 0x77, 0x3d, 0xa7, 0x13, 0xde, 0xd7, 0x49,
	0xb6, 0xdc, 0xfb, 0xb7, 0xee, 0xb1, 0xb7, 0x3a, 0xe1, 0xf5, 0x02, 0x0a, 0xd1, 0x41, 0x84, 0x7d,
	0xe3, 0x2d, 0x0d, 0x13, 0x8b, 0x8f, 0xc7, 0x30, 0xb2, 0x14, 0x1b, 0xf7, 0x26, 0xd3, 0x4c, 0xf4,
	0x10, 0xd5, 0x0f, 0x50, 0x88, 0xc8, 0xef, 0x25, 0x7b, 0x91, 0x55, 0xd3, 0xd2, 0x80, 0x8b, 0x8f,
	0x17, 0x00, 0x86, 0xa9, 0x89, 0xf4, 0xec, 0x5a, 0x92, 0xf1, 0x26, 0xfa, 0x47, 0x66, 0xee, 0xe0,
	0x50, 0xc4, 0x9e, 0x88, 0x37, 0xce, 0x10, 0xbe, 0xc0, 0xf4, 0x56, 0x5e, 0x53, 0x8b, 0xab, 0x1d,
	0x9b, 0x7c, 0x9f, 0xfb, 0xec, 0x72, 0x07, 0xb6, 0x3d, 0xfb, 0x72, 0x24, 0x7f, 0xb8, 0xf8, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0xae, 0x1b, 0xb3, 0xd2, 0xde, 0x01, 0x00, 0x00,
}
