// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/stock/stock.proto

package go_micro_secbuy_srv_stock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 商品
type Commodity struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Sale                 int32    `protobuf:"varint,4,opt,name=sale,proto3" json:"sale,omitempty"`
	CreateTime           string   `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commodity) Reset()         { *m = Commodity{} }
func (m *Commodity) String() string { return proto.CompactTextString(m) }
func (*Commodity) ProtoMessage()    {}
func (*Commodity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{0}
}

func (m *Commodity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commodity.Unmarshal(m, b)
}
func (m *Commodity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commodity.Marshal(b, m, deterministic)
}
func (m *Commodity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commodity.Merge(m, src)
}
func (m *Commodity) XXX_Size() int {
	return xxx_messageInfo_Commodity.Size(m)
}
func (m *Commodity) XXX_DiscardUnknown() {
	xxx_messageInfo_Commodity.DiscardUnknown(m)
}

var xxx_messageInfo_Commodity proto.InternalMessageInfo

func (m *Commodity) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Commodity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Commodity) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Commodity) GetSale() int32 {
	if m != nil {
		return m.Sale
	}
	return 0
}

func (m *Commodity) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

// 查看商品信息的请求
type GetRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 结果
type Response struct {
	Success              bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Commodity            *Commodity `protobuf:"bytes,3,opt,name=commodity,proto3" json:"commodity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetCommodity() *Commodity {
	if m != nil {
		return m.Commodity
	}
	return nil
}

// 错误信息
type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f076fe61217ff59, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*Commodity)(nil), "go.micro.secbuy.srv.stock.Commodity")
	proto.RegisterType((*GetRequest)(nil), "go.micro.secbuy.srv.stock.GetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.secbuy.srv.stock.Response")
	proto.RegisterType((*Error)(nil), "go.micro.secbuy.srv.stock.Error")
}

func init() { proto.RegisterFile("proto/stock/stock.proto", fileDescriptor_5f076fe61217ff59) }

var fileDescriptor_5f076fe61217ff59 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0xbe, 0xa6, 0x5f, 0x3b, 0x2d, 0x0a, 0x8b, 0xe8, 0x2a, 0x22, 0x25, 0x2a, 0xf4,
	0xb4, 0x42, 0x0b, 0x3e, 0x80, 0x45, 0x7a, 0xdf, 0x7a, 0x12, 0x2f, 0xe9, 0x66, 0x90, 0xc5, 0xa4,
	0x5b, 0x77, 0x37, 0x85, 0xbe, 0x8b, 0x07, 0x1f, 0x55, 0x32, 0x49, 0x1b, 0x11, 0x0c, 0x3d, 0x78,
	0x09, 0x33, 0xc3, 0x6f, 0xfe, 0x99, 0xf9, 0xcf, 0xc2, 0xd9, 0xda, 0x1a, 0x6f, 0xee, 0x9c, 0x37,
	0xea, 0xad, 0xfa, 0x0a, 0xaa, 0xb0, 0xf3, 0x57, 0x23, 0x72, 0xad, 0xac, 0x11, 0x0e, 0xd5, 0xb2,
	0xd8, 0x0a, 0x67, 0x37, 0x82, 0x80, 0x78, 0x0b, 0xfd, 0x99, 0xc9, 0x73, 0x93, 0x6a, 0xbf, 0x65,
	0x47, 0x10, 0xea, 0x94, 0x07, 0xa3, 0x60, 0x1c, 0xc9, 0x50, 0xa7, 0x8c, 0x41, 0x67, 0x95, 0xe4,
	0xc8, 0xc3, 0x51, 0x30, 0xee, 0x4b, 0x8a, 0xd9, 0x09, 0x44, 0xca, 0x14, 0x2b, 0xcf, 0xff, 0x11,
	0x56, 0x25, 0x25, 0xe9, 0x92, 0x0c, 0x79, 0x87, 0x8a, 0x14, 0xb3, 0x2b, 0x00, 0x65, 0x31, 0xf1,
	0xf8, 0xa4, 0x73, 0xe4, 0x11, 0x69, 0x7c, 0xab, 0xc4, 0x97, 0x00, 0x73, 0xf4, 0x12, 0xdf, 0x0b,
	0x74, 0xfe, 0xe7, 0xbf, 0xe3, 0xcf, 0x00, 0x7a, 0x12, 0xdd, 0xda, 0xac, 0x1c, 0x32, 0x0e, 0xff,
	0x5d, 0xa1, 0x14, 0x3a, 0x47, 0x44, 0x4f, 0xee, 0x52, 0x76, 0x0f, 0x11, 0x5a, 0x6b, 0x2c, 0xcd,
	0x38, 0x98, 0x8c, 0xc4, 0xaf, 0xab, 0x8a, 0xc7, 0x92, 0x93, 0x15, 0xce, 0x1e, 0xa0, 0xaf, 0x76,
	0x7b, 0xd3, 0x2a, 0x83, 0xc9, 0x4d, 0x4b, 0xef, 0xde, 0x23, 0xd9, 0xb4, 0xc5, 0x53, 0x88, 0x48,
	0xb3, 0xdc, 0x5e, 0x99, 0x14, 0xeb, 0xe9, 0x29, 0x66, 0xa7, 0xd0, 0x4d, 0xd1, 0x27, 0x3a, 0xab,
	0xdd, 0xab, 0xb3, 0xc9, 0x47, 0x08, 0xc3, 0x45, 0xa9, 0xb9, 0x40, 0xbb, 0xd1, 0x0a, 0xd9, 0x0b,
	0x1c, 0xcf, 0xc8, 0x94, 0xe6, 0x0e, 0x07, 0x4d, 0x72, 0x71, 0xdd, 0x42, 0xed, 0x9d, 0x7b, 0x86,
	0xe1, 0x1c, 0x7d, 0x23, 0x7d, 0xdb, 0xd2, 0xd4, 0x5c, 0xe3, 0x30, 0x6d, 0x09, 0x9d, 0x05, 0x66,
	0xd9, 0x5f, 0x6a, 0x2e, 0xbb, 0xf4, 0x62, 0xa7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xc2,
	0xcf, 0x0e, 0xcc, 0x02, 0x00, 0x00,
}
